call extend(g:php_constants, {
\ 'DATE_ATOM': '',
\ 'DATE_COOKIE': '',
\ 'DATE_ISO8601': '',
\ 'DATE_RFC822': '',
\ 'DATE_RFC850': '',
\ 'DATE_RFC1036': '',
\ 'DATE_RFC1123': '',
\ 'DATE_RFC2822': '',
\ 'DATE_RFC3339': '',
\ 'DATE_RSS': '',
\ 'DATE_W3C': '',
\ 'SUNFUNCS_RET_TIMESTAMP': '',
\ 'SUNFUNCS_RET_STRING': '',
\ 'SUNFUNCS_RET_DOUBLE': '',
\ 'LC_TIME': '',
\ })
