call extend(g:php_constants, {
\ 'FRIBIDI_CHARSET_UTF8': '',
\ 'FRIBIDI_CHARSET_8859_6': '',
\ 'FRIBIDI_CHARSET_8859_8': '',
\ 'FRIBIDI_CHARSET_CP1255': '',
\ 'FRIBIDI_CHARSET_CP1256': '',
\ 'FRIBIDI_CHARSET_ISIRI_3342': '',
\ 'FRIBIDI_CHARSET_CAP_RTL': '',
\ 'FRIBIDI_RTL': '',
\ 'FRIBIDI_LTR': '',
\ 'FRIBIDI_AUTO': '',
\ })
