call extend(g:php_constants, {
\ 'SQLTEXT': '',
\ 'SQLVARCHAR': '',
\ 'SQLCHAR': '',
\ 'SQLINT1': '',
\ 'SQLINT2': '',
\ 'SQLINT4': '',
\ 'SQLBIT': '',
\ 'SQLFLT4': '',
\ 'SQLFLT8': '',
\ 'SQLFLTN': '',
\ 'MSSQL_ASSOC': '',
\ 'MSSQL_NUM': '',
\ 'MSSQL_BOTH': '',
\ })
