call extend(g:php_constants, {
\ 'MYSQLND_QC_CONDITION_META_SCHEMA_PATTERN': '',
\ 'MYSQLND_QC_SERVER_ID_SWITCH': '',
\ 'MYSQLND_QC_VERSION': '',
\ 'MYSQLND_QC_VERSION_ID': '',
\ 'MYSQLND_QC_ENABLE_SWITCH': '',
\ 'MYSQLND_QC_DISABLE_SWITCH': '',
\ 'MYSQLND_QC_TTL_SWITCH': '',
\ })
