call extend(g:php_constants, {
\ 'PHP_OUTPUT_HANDLER_STDFLAGS': '',
\ 'PHP_OUTPUT_HANDLER_CLEANABLE': '',
\ 'PHP_OUTPUT_HANDLER_FLUSHABLE': '',
\ 'PHP_OUTPUT_HANDLER_REMOVABLE': '',
\ 'PHP_OUTPUT_HANDLER_START': '',
\ 'PHP_OUTPUT_HANDLER_WRITE': '',
\ 'PHP_OUTPUT_HANDLER_FLUSH': '',
\ 'PHP_OUTPUT_HANDLER_CLEAN': '',
\ 'PHP_OUTPUT_HANDLER_FINAL': '',
\ 'PHP_OUTPUT_HANDLER_CONT': '',
\ 'PHP_OUTPUT_HANDLER_END': '',
\ })
