call extend(g:php_constants, {
\ 'PTHREADS_INHERIT_ALL': '',
\ 'PTHREADS_INHERIT_INI': '',
\ 'PTHREADS_INHERIT_CONSTANTS': '',
\ 'PTHREADS_INHERIT_CLASSES': '',
\ 'PTHREADS_INHERIT_FUNCTIONS': '',
\ 'PTHREADS_INHERIT_INCLUDES': '',
\ 'PTHREADS_INHERIT_NONE': '',
\ })
