call extend(g:php_constants, {
\ 'READ_AHEAD': '',
\ 'MIT_NEED_ALL': '',
\ 'MIT_KEYS_ASSOC': '',
\ 'CALL_TOSTRING': '',
\ 'CATCH_GET_CHILD': '',
\ 'RIT_LEAVES_ONLY': '',
\ 'LOCK_SH': '',
\ 'LOCK_EX': '',
\ 'LOCK_UN': '',
\ 'LOCK_NB': '',
\ 'SEEK_SET': '',
\ 'SEEK_CUR': '',
\ 'SEEK_END': '',
\ 'PHP_INT_MAX': '',
\ })
