call extend(g:php_constants, {
\ 'XSL_CLONE_AUTO': '',
\ 'XSL_CLONE_NEVER': '',
\ 'XSL_CLONE_ALWAYS': '',
\ 'LIBXSLT_VERSION': '',
\ 'LIBXSLT_DOTTED_VERSION': '',
\ 'LIBEXSLT_VERSION': '',
\ 'LIBEXSLT_DOTTED_VERSION': '',
\ 'XSL_SECPREF_READ_FILE': '',
\ 'XSL_SECPREF_WRITE_FILE': '',
\ 'XSL_SECPREF_CREATE_DIRECTORY': '',
\ 'XSL_SECPREF_READ_NETWORK': '',
\ 'XSL_SECPREF_WRITE_NETWORK': '',
\ })
