call extend(g:php_constants, {
\ 'XSLT_SABOPT_PARSE_PUBLIC_ENTITIES': '',
\ 'XSLT_SABOPT_DISABLE_ADDING_META': '',
\ 'XSLT_SABOPT_DISABLE_STRIPPING': '',
\ 'XSLT_SABOPT_IGNORE_DOC_NOT_FOUND': '',
\ 'XSLT_OPT_SILENT': '',
\ 'XSLT_SABOPT_FILES_TO_HANDLER': '',
\ 'XSLT_ERR_UNSUPPORTED_SCHEME': '',
\ })
