call extend(g:php_constants, {
\ 'YAF_VERSION': '',
\ 'YAF_ENVIRON': '',
\ 'YAF_ERR_STARTUP_FAILED': '',
\ 'YAF_ERR_ROUTE_FAILED': '',
\ 'YAF_ERR_DISPATCH_FAILED': '',
\ 'YAF_ERR_AUTOLOAD_FAILED': '',
\ 'YAF_ERR_NOTFOUND_MODULE': '',
\ 'YAF_ERR_NOTFOUND_CONTROLLER': '',
\ 'YAF_ERR_NOTFOUND_ACTION': '',
\ 'YAF_ERR_NOTFOUND_VIEW': '',
\ 'YAF_ERR_CALL_FAILED': '',
\ 'YAF_ERR_TYPE_ERROR': '',
\ })
