call extend(g:php_constants, {
\ 'YPERR_ACCESS': '',
\ 'YPERR_BADARGS': '',
\ 'YPERR_BADDB': '',
\ 'YPERR_BUSY': '',
\ 'YPERR_DOMAIN': '',
\ 'YPERR_KEY': '',
\ 'YPERR_MAP': '',
\ 'YPERR_NODOM': '',
\ 'YPERR_NOMORE': '',
\ 'YPERR_PMAP': '',
\ 'YPERR_RESRC': '',
\ 'YPERR_RPC': '',
\ 'YPERR_YPBIND': '',
\ 'YPERR_YPERR': '',
\ 'YPERR_YPSERV': '',
\ 'YPERR_VERS': '',
\ })
